#!/bin/bash

###### createMakefile [filename_string $1] [extension_string $2]
createMakefile()    {
    touch Makefile;
###### CREATE HEADER FOR MAKEFILE
    cat << EOF > Makefile
################################### #
# Makefile by Inland Make-maker     #
# https://github.com/bg2slc/inland  #
# DISCLAIMER:                       #
# This makefile is made by a simple #
# script, and should only be        #
# trusted with simple projects.     #
#####################################
EOF
    if [[ "$ext" == "cpp" ]]; then
###### CREATE BODY WHEN SOURCE FILE IS .CPP
        echo -e "
compile:
\tg++ $@ -g -o $1.bin

clean:
\t@rm -f $1.bin

run:
\t./$1.bin

all:
\tcompile
\trun" >> Makefile
        echo "Makefile created for $1.$2"
    elif [[ "$ext" == "cs" ]]; then
###### CREATE BODY WHEN SOURCE FILE IS .CS
        echo "
$1.bin: $1.$2
#\t@mcs -out:$1.bin $@ -r:System.Windows.Forms.dll,System.Drawing.dll
\t@mcs -out:$1.bin $@

clean:
\t@rm -f $1.bin

run: $1.bin
\t@mono $1.bin

all: run" >> Makefile
    fi
}



###### MAIN FUNCTION

OPTION=$((RANDOM % 7))
quotes=(
"   TRUE LOVE IS POSSIBLE, ONLY IN THE NEXT WORLD, FOR NEW PEOPLE. IT'S TOO LATE FOR US. WREAK HAVOC ON THE MIDDLE CLASS."
"   INLAND EMPIRE: This is a man with a lot of past, but little present. And almost no future"
"   VOLITION: It's better to know you're being played than to be played without knowing it, is it not?"
"   THE DESERTER: Men without ideals are only animals."
"   VOLITION: This is somewhere to be. This is all you have, but it's still something. Streets and sodium lights. The sky, the world. You're still alive."
"   INLAND EMPIRE: WHERE DA HOOD, WHERE DA HOOD, WHERE DA HOOD AT.\n
   SHIVERS: GOT A BROTHER IN THE CUT, WHERE THE WOOD AT."
"   HALF-LIGHT: Never forget: The whole world's a wooden house and you're a goddamn flamethrower."
)
echo -e "${quotes[$OPTION]}"
echo ""
if [[ "$1" == "" ]]; then
    echo -e "No file selected. Exiting..."
    exit
fi

file=${1%.*}
ext=${1##*.}
full_param=$@


read -p "Makefile for $ext, binary will be called $file.bin.
Treating $1 as containing the main method. Continue? (Y/n): "
if [[ "$REPLY" == "" || "$REPLY" == "Y"|| "$REPLY" == "y" ]]; then
    echo -e "Confirmed. Generating..."
    createMakefile $file $ext $full_param
else
    echo -e "Exiting..."
fi


