#!/bin/bash

createMakefile()    {
    touch Makefile;
###### CREATE HEADER FOR MAKEFILE
    cat << EOF > Makefile
####################################
# Makefile by Inland Make-maker    #
# https://github.com/bg2slc/inland #
####################################
EOF
    if [[ "$ext" == "cpp" ]]; then
###### CREATE BODY WHEN SOURCE FILE IS .CPP
        echo "
all:
    compile
    run

compile:
    g++ $1.$2 -g -o $1.bin

clean:
    @rm -f $1.bin

run:
    ./$1.bin" >> Makefile
        echo "Makefile created for $1.$2"
    elif [[ "$ext" == "cs" ]]; then
###### CREATE BODY WHEN SOURCE FILE IS .CS
        echo "
all: run

$1.bin: $1.$2
#   @mcs -out:$1.bin $1.$2 -r:System.Windows.Forms.dll,System.Drawing.dll
    @mcs -out:$1.bin $1.$2

clean:
    @rm -f $1.bin

run: $1.bin
    @mono $1.bin" >> Makefile
    fi
}



###### MAIN FUNCTION

OPTION=$((RANDOM % 4))
case $OPTION in
    1) echo "   INLAND EMPIRE: This is a man with a lot of past, but little present. And almost no future"
        ;;
    2) echo "   VOLITION: It's better to know you're being played than to be played without knowing it, is it not?"
        ;;
    3) echo "   THE DESERTER: Men without ideals are only animals."
        ;;
    4) echo "   VOLITION: This is somewhere to be. This is all you have, but it's still something. Streets and sodium lights. The sky, the world. You're still alive."
        ;;
esac

echo ""

if [[ "$1" == "" ]]; then
    echo -e "No file selected. Exiting..."
    exit
fi

file=${1%.*}
ext=${1##*.}


read -p "Makefile for $ext, binary will be called $file.bin. Continue? (Y/n): "
if [[ "$REPLY" == "" || "$REPLY" == "Y"|| "$REPLY" == "y" ]]; then
    echo -e "Confirmed. Generating..."
    createMakefile $file $ext
else
    echo -e "Exiting..."
fi


